steps:
  - name: hashicorp/terraform:1.9
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform-config
        terraform init || exit
        terraform fmt  || exit
        terraform validate || exit

  - name: hashicorp/terraform:1.9
    entrypoint: sh
    args:
      - -c
      - |
        cd terraform-config
        terraform plan -no-color || exit
        terraform apply -auto-approve -no-color || exit

options:
  logging: CLOUD_LOGGING_ONLY