apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app:  app-test
  replicas: 3
  template:
    metadata:
      labels:
        app:  app-test
    spec:
      containers:
      - name: app-container
        image: azoistar10/app-test:V1
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app:  app-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: app-test.local.com
    http:
      paths:
      - path: /
        backend:
          service:
            name: app-service
            port:
              number: 80


